### ISSUE TITLE
A “first patch” section?

### ISSUE THREAD

**Issue by joefiorini** [VCVRack/manual#17]
I just found Rack a few days ago and am having a great time with it. However, one thing I found confusing at first was making a basic, useful patch out of only Core/Fundamental plugins. I ended up watching a video on YouTube that was more general modular synthesis, but it helped me figure out the sequence for wiring ADSR, VCO, VCF, VCA.

I would have loved a short guide that walks through making that basic patch. For accessibility I would start with a MIDI plugin set to Computer Keyboard, then add some of the basic components (VCO -> VCF -> VCA -> Audio, and then an ADSR connected to the VCA) needed to produce nice sounds.

I know the guide doesn’t have anything to do with plugins typically, but would you consider a PR that included something like this?

**Comment by AndrewBelt** [comment]
Have you read https://vcvrack.com/manual/QuickStart.html?

**Comment by AndrewBelt** [comment]
Now at https://manual.vcvrack.com/GettingStarted
