### ISSUE TITLE
Build instructions should include libegl1-mesa-dev

### ISSUE THREAD

**Issue by ndrspcfd** [VCVRack/manual#24]
(Ubuntu 18.04 following 16.04)

Running the documented setup command gave me KHR/khrplatform.h no such file or directory.

Fixed by adding libegl1-mesa-dev to the apt install command.

**Comment by AndrewBelt** [comment]
Installing the headers for an OpenGL implementation is dependent on your graphics card, so your solution won't work for everybody.

**Comment by ndrspcfd** [comment]
That makes a lot  of sense :) Thanks for the quick response.
