### ISSUE TITLE
Entry on how to write efficient plugins?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/manual#3]
Would that be a suitable topic for a section of the manual? Of would it be kind of off-topic?

**Comment by AndrewBelt** [comment]
It would help people, so go ahead. If it's DSP-related, put it in DSP. Otherwise, make a new section.

**Comment by squinkylabs** [comment]
Was thinking of putting some links at the bottom to code examples. Of course they would initially be links to our repo. Would that be useful, or just shameless self promotion? I guess we could decide at PR review time.

**Comment by squinkylabs** [comment]
Making progress. It's getting a little long, but some editing... What's the best way to get feedback from you (after I get others to review)? Just put up a PR?

**Comment by AndrewBelt** [comment]
If you don't want to merge yet, just push to your own GitHub fork and someone can give feedback.

**Comment by AndrewBelt** [comment]
I assume this is obsolete, so closing.
