### ISSUE TITLE
Distribute PDF manual

### ISSUE THREAD

**Issue by 4tip** [VCVRack/manual#45]
Hi. Could you release a offline PDF-Manual please?

**Comment by AndrewBelt** [comment]
You could run `make latexpdf` in this repo, but I haven't spent a second checking the output of this. Formulas and SVG don't work, but here's an example build [VCVRack.pdf](https://github.com/VCVRack/manual/files/5720361/VCVRack.pdf)

**Comment by AndrewBelt** [comment]
Since the VCV Manual has moved to https://manual.vcvrack.com/, there is unfortunately no longer a way to generate a PDF manual unless you scrape the HTML and assemble a PDF from its pages.
