### ISSUE TITLE
Section Links not supported?

### ISSUE THREAD

**Issue by patman023** [VCVRack/manual#6]
https://help.github.com/articles/basic-writing-and-formatting-syntax/#section-links

**Comment by AndrewBelt** [comment]
Explain what's wrong and what you should expect? You can do something like `[toolbar](Toolbar.md)` and it seems to work fine.

**Comment by patman023** [comment]
Apologies, I must have Pasted the link over the description.

Trying to write a submenu in (a fork of) Core.md (Linked so one can skip to the module they want to read about), but I haven't been able to expose the relevant header-based section links.

**Comment by patman023** [comment]
Figured it out. 

and doubly figured another problem fix - everything after # in the link MUST be lowercase, even if the section header contains uppercase.

**Comment by AndrewBelt** [comment]
Yes, and all special characters and whitespace are replaced with `-`
